### ISSUE TITLE
HUB_KUSTOMIZE_TARBALL_SUBPATHS should  allow files

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub-extensions#109]
Today user can define tarball subpath via environment variable `HUB_KUSTOMIZE_TARBALL_SUBPATHS` allow to refer directories. 

- [x] Parameter referneced by this env should allow user to refer a file (not only a directory)
- [x] If file (or directory) referenced by the env is not found, deployment should stop with error
- [x] Another improvement `:` to define destination in `./kustomize` directory should be optional

See example:

```yaml
parameters:
- name: kustomize.tarball.subpaths
  env: HUB_KUSTOMIZE_TARBALL_SUBPATHS
  value: >-
    common/kubeflow-roles/base
    common/istio-1-14/kubeflow-istio-resources/base/cluster-roles.yaml
```
