### ISSUE TITLE
Unable to use kubernetes executor

### ISSUE THREAD

**Issue by TheRealSpaceShip** [agilestacks/hub-extensions#111]
If a user is using `kubernetes` executor by setting `HUB_DEPLOY_PROFILE="kubernetes"` a stack deployment fails with the next error:

```text
Running pre deploy hook: kubernetes
* Using kubeconfig:/home/igor_lysak/agilestacks/stacks_examples/simple-rancher/.hub/env/localhost.kubeconfig
* Checking connectivity to cluster: Connected

Proceeding with: deploy
* Using profile: kubernetes
* Running CLI command:

  $ hubctl deploy /home/igor_lysak/agilestacks/stacks_examples/simple-rancher/.hub/localhost.elaborate -s /home/igor_lysak/agilestacks/stacks_examples/simple-rancher/.hub/localhost.state
2023/09/07 17:47:17 Unable to load state: file does not exist
Stack localhost not found
```

Steps to reproduce:

1. Create a stack with the next `hub.yaml`:

```yaml
kind: stack
version: 1

requires:
- kubernetes

extensions:
  configure:
  - kubernetes
  - env
  deploy:
    before:
    - kubernetes

components:
- name: cert-manager
  source:
    dir: components/cert-manager
    git:
      remote: https://github.com/epam/hub-kubeflow-components.git
      subDir: cert-manager

parameters:
- name: dns.domain
  value: localhost
```

2. Run `hubctl stack init`
3. Run `hubctl stack deploy`

Actual result: Deploy is failing with an error
Expected result: Deploy should be run in the Kubernetes cluster
