### ISSUE TITLE
Failed to get component with ref as a git tag

### ISSUE THREAD

**Issue by TheRealSpaceShip** [agilestacks/hub-extensions#29]
There is a error `error: pathspec 'origin/v1.2.0' did not match any file(s) known to git` when user run `hub stack init` with next `hub.yaml` components configuration

```yaml
version: 1
kind: stack
...
components:
  ...
  - name: istio-ingressgateway
    source:
      dir: components/istio-ingressgateway
      git:
        remote: https://github.com/agilestacks/kubeflow-components.git
        subDir: istio-ingressgateway
        ref: v1.2.0
    depends:
      - istio
  ...
```

In this example `ref: v1.2.0` is a git tag.
