### ISSUE TITLE
`hubctl stack init <statefile>` command does not recover certain env parameters from state

### ISSUE THREAD

**Issue by oginskis** [agilestacks/hub-extensions#72]
Steps to reproduce:
1. Create a stack template with one or few parameters defined with a `component` discriminator, for example:

```
- name: ingress
  component: mlflow
  parameters:
  - name: hosts
    fromEnv: MY_COOL_ENV_VAR
```
2. Init, configure, and deploy the stack.
3. Verify that `MY_COOL_ENV_VAR` value is present in the `.env` file
4. Re-initialize the `stack` from `state`: `hubctl stack init <statefile ref>`
5. `MY_COOL_ENV_VAR` is not present in the `.env` file and a user is asked to enter it again on `hubctl stack configure`

Expected:
`MY_COOL_ENV_VAR` should be present in the `.env` file.
