### ISSUE TITLE
Incorrect behaviour of params -c <component> value <val> 

### ISSUE THREAD

**Issue by oginskis** [agilestacks/hub-extensions#80]
I have component parameters defined as follows (the order of parameters matters):
```
- name: kubernetes
  component: external-dns
  parameters:
  - name: namespace
    value: ns-a
  - name: serviceAccount
    value: account-a

- name: kubernetes
  component: cert-manager
  parameters:
  - name: namespace
    value: ns-b
  - name: serviceAccount
    value: account-b 
```
When I do (from extension):
`params -c cert-manager value kubernetes.serviceAccount`
I get `ns-b` which is correct

However, when I do:
`params -c external-dns value kubernetes.serviceAccount`
I still get `ns-b` which is not correct

Please fix
