### ISSUE TITLE
Allow users to define multiple CRDs separated by whitespace

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub-extensions#83]
Allow users to define parameters like the following 

```yaml
parameters
- name: helm.chart.crd
  env: CRD
  value: >-
    https://raw.githubusercontent.com/istio/istio/master/manifests/charts/base/crds/crd-all.gen.yaml
    https://raw.githubusercontent.com/istio/istio/master/manifests/charts/base/crds/crd-operator.yaml
```

- [x] Apply for `helm` extension
- [x] Apply for `kustomize` extension
