### ISSUE TITLE
Add helm tarball chart support

### ISSUE THREAD

**Issue by seseque** [agilestacks/hub-extensions#94]
Ability to assign to HELM_CHART url to download tar archive with helm-chart

**Comment by akranga** [comment]
As a user I want to add a parameter

```yaml
parameters:
- name: helm.chart
  value: https://github.com/aws/karpenter/raw/main/charts/karpenter-0.9.1.tgz
  env: HELM_CHART
```

Then `helm` extension should:
- [x] Download a helm chart
- [x] Unpack to the temp dir
- [x] Install from the temp dir (similar as we do today with tarball file hosted locally)
- [x] Update documentation https://hubctl.io/reference/components/helm/
